//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class FlightTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightTicket()
        {
            this.Orders = new HashSet<Order>();
        }

        public int flightID { get; set; }


        public Nullable<int> customerID { get; set; }

        [Display(Name = "Flight Destanation")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string flightDestanation { get; set; }

        [Display(Name = "Fligh Go Date")]
        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> flighGoDate { get; set; }

        [Display(Name = "Flight Back Date")]
        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> flightBackDate { get; set; }

        [Display(Name = "Flight Connection")]
        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<int> flightConnection { get; set; }

        [Display(Name = "Flight Gate")]
        public string flightGate { get; set; }

        [Display(Name = "Flight Seat")]
        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<int> flightSeat { get; set; }

        [Display(Name = "Flight Air Company")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string flightAirCompany { get; set; }

        [Display(Name = "Flight Ticket Quantity")]
        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<int> flightTicketQuantity { get; set; }

        [Display(Name = "Flight Department")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string flightDepartment { get; set; }


        [Display(Name = "Flight Ticket Picture")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string flightTicketPicture { get; set; }

        public HttpPostedFileBase imageFile { get; set; }



        [Display(Name = "Flight Row")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string flightRow { get; set; }


        [Display(Name = "Flight Number")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string flightNumber { get; set; }

        [Display(Name = "Flight Go Time")]
        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> flightGoTime { get; set; }


        [Display(Name = "Flight Back Time")]
        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> flightBackTime { get; set; }

        [Display(Name = "Flight Active")]
        public Nullable<bool> flightActive { get; set; }


        [Display(Name = "Flight Price")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string flightPrice { get; set; }


        [Display(Name = "Flight Info")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string flightInfo { get; set; }

        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}