//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> flightID { get; set; }
        public string orderPrice { get; set; }
        public string orderDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual FlightTicket FlightTicket { get; set; }
    }
}
